name = "d1-template"
main = "src/index.ts"
compatibility_date = "2024-02-08"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "darkchat-db"
database_id = "e33f74f0-2690-47e9-85b0-58d3c52d64b5"